version: '3.8'

services:
  bot-dukal:
    image: cotizador-bot-dukal
    container_name: bot-dukal-autos
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TOKEN_PERMANENTE=EAARcdnxlZCXkBSrm6r4RjesgE3rayQLRF5re3aG4IcTftSGuts7vauOMnkybfmulXnlsIZCnQf0yH41ZAFcoXR6SEvSqDwiGazyHjOukflxkZCn0UNZBWZCWzbx3ZBtSVN9IptXNWvhWRS3kD31QSlp7kZCYnYIxli34vedTfb46LkrzPUaYrYnv095FXBzZBJAZDZD
      - PHONE_NUMBER_ID=1332205446647554
      - VERIFY_TOKEN=dukal_token_secreto_123
    networks:
      - red_bot

networks:
  red_bot:
    driver: bridge
